export const Data = [
    Itemse = [
        { 
          id: 0,
          title: "Samsung S21",
          description: "black in color",
          price: "2500",
          img: "./images/mobile1.png",
          quantity: 1,
    
          
        },
        {
          id: 1,
          title: "Samsung M21",
          description: "white in color",
          price: "2300",
          img: "./images/mobile2.png",
          quantity: 1,
          
        },
        {
          id: 2,
          title: "Redmi 9",
          description: "black in color",
          price: "3500",
          img: "./images/mobile1.png",
          quantity: 1,
          
        },
        {
          id: 3,
          title: "Iphone 12",
          description: "Best mobile ever",
          price: "90500",
          img: "./images/mobile3.png",
          quantity: 1,
          
        },
        {
          id: 4,
          title: "Samsung S21",
          description: "black in color",
          price: "2500",
          img: "./images/mobile1.png",
          quantity: 1,
          
        },
        {
          id: 5,
          title: "Redmi 9",
          description: "black in color",
          price: "3500",
          img: "./images/mobile2.png",
          quantity: 1,
          
        },
        {
          id: 6,
          title: "Samsung S21",
          description: "black in color",
          price: "2500",
          img: "./images/mobile3.png",
          quantity: 1,
          
        },
        {
          id: 7,
          title: "Iphone 12",
          description: "Best mobile ever",
          price: "90500",
          img: "./images/mobile1.png",
          quantity: 1,
          
        },
        {
          id: 8,
          title: "Samsung S21",
          description: "black in color",
          price: "2500",
          img: "./images/mobile2.png",
          quantity: 1,
          
        },
      ],
      Itemsf = [
        {
          id: 9,
          title: "frock",
          description: "black in color",
          price: "2500",
          img: "./images/fashion1.png",
          quantity: 1,
        },
        {
          id: 10,
          title: "Color Valley",
          description: "white in color",
          price: "2300",
          img: "./images/fashion2.png",
          quantity: 1,
        },
        {
          id: 11,
          title: "Long generic",
          description: "black in color",
          price: "3500",
          img: "./images/fashion3.png",
          quantity: 1,
        },
        {
          id: 12,
          title: "Purvaja",
          description: "Best dress ever",
          price: "90500",
          img: "./images/fashion4.png",
          quantity: 1,
        },
        {
          id: 13,
          title: "frock",
          description: "black in color",
          price: "2500",
          img: "./images/fashion1.png",
          quantity: 1,
        },
        {
          id: 14,
          title: "Long generic",
          description: "black in color",
          price: "3500",
          img: "./images/fashion2.png",
          quantity: 1,
        },
        {
          id: 15,
          title: "Color Valley",
          description: "black in color",
          price: "2500",
          img: "./images/fashion3.png",
          quantity: 1,
        },
        {
          id: 16,
          title: "Purvaja",
          description: "Best dress ever",
          price: "90500",
          img: "./images/fashion4.png",
          quantity: 1,
        },
        {
          id: 17,
          title: "Frock",
          description: "black in color",
          price: "2500",
          img: "./images/fashion1.png",
          quantity: 1,
        },
      ],
      Itemsh = [
        {
          id: 18,
          title: "Pride Prejudice",
          description: "by Jane Austen",
          price: "2500",
          img: "./images/book1.png",
          quantity: '1',
        },
        {
          id: 19,
          title: "Wuthering",
          description: "by Emily Bronte",
          price: "2300",
          img: "./images/book2.png",
          quantity: '1',
        },
        {
          id: 20,
          title: "Girl In Room",
          description: "by Chetan Bhagat",
          price: "3500",
          img: "./images/book3.png",
          quantity: '1',
        },
        {
          id: 21,
          title: "As men Think",
          description: "by James Allen",
          price: "90500",
          img: "./images/book4.png",
          quantity: '1',
        },
        {
          id: 22,
          title: "Pride Prejudice",
          description: "by Jane Austen",
          price: "2500",
          img: "./images/book1.png",
          quantity: '1',
        },
        {
          id: 23,
          title: "Wuthering",
          description: "by Emily Bronte",
          price: "3500",
          img: "./images/book2.png",
          quantity: '1',
        },
        {
          id: 24,
          title: "Girl In Room",
          description: "by Chetan Bhagat",
          price: "2500",
          img: "./images/book3.png",
          quantity: '1',
        },
        {
          id: 25,
          title: "As men Think",
          description: "by James Allen",
          price: "90500",
          img: "./images/book4.png",
          quantity: '1',
        },
        {
          id: 26,
          title: "Pride Prejudice",
          description: "By Jane Austen",
          price: "2500",
          img: "./images/book1.png",
          quantity: '1',
        },
      ]
]
