export const Itemsh = [
    {
      id: 0,
      title: "Pride Prejudice",
      description: "by Jane Austen",
      price: 2500,
      img: "./images/book1.png",
      quantity: 3,
    },
    {
      id: 1,
      title: "Wuthering",
      description: "by Emily Bronte",
      price: 2300,
      img: "./images/book2.png",
      quantity: 3,
    },
    {
      id: 2,
      title: "Girl In Room",
      description: "by Chetan Bhagat",
      price: 3500,
      img: "./images/book3.png",
      quantity: 3,
    },
    {
      id: 3,
      title: "As men Think",
      description: "by James Allen",
      price: 90500,
      img: "./images/book4.png",
      quantity: 3,
    },
    {
      id: 4,
      title: "Pride Prejudice",
      description: "by Jane Austen",
      price: 2500,
      img: "./images/book1.png",
      quantity: 3,
    },
    {
      id: 5,
      title: "Wuthering",
      description: "by Emily Bronte",
      price: 3500,
      img: "./images/book2.png",
      quantity: 3,
    },
    {
      id: 6,
      title: "Girl In Room",
      description: "by Chetan Bhagat",
      price: 2500,
      img: "./images/book3.png",
      quantity: 3,
    },
    {
      id: 7,
      title: "As men Think",
      description: "by James Allen",
      price: 90500,
      img: "./images/book4.png",
      quantity: '1',
    },
    {
      id: 8,
      title: "Pride Prejudice",
      description: "By Jane Austen",
      price: 2500,
      img: "./images/book1.png",
      quantity: 3,
    },
  ]; 