export const Itemsf = [
    {
      id: 0,
      title: "frock",
      description: "black in color",
      price: 2500,
      img: "./images/fashion1.png",
      quantity: 2,
    },
    {
      id: 1,
      title: "Color Valley",
      description: "white in color",
      price: 2300,
      img: "./images/fashion2.png",
      quantity: 2,
    },
    {
      id: 2,
      title: "Long generic",
      description: "black in color",
      price: 3500,
      img: "./images/fashion3.png",
      quantity: 2,
    },
    {
      id: 3,
      title: "Purvaja",
      description: "Best dress ever",
      price: 90500,
      img: "./images/fashion4.png",
      quantity: 2,
    },
    {
      id: 4,
      title: "frock",
      description: "black in color",
      price: 2500,
      img: "./images/fashion1.png",
      quantity: 2,
    },
    {
      id: 5,
      title: "Long generic",
      description: "black in color",
      price: 3500,
      img: "./images/fashion2.png",
      quantity: 2,
    },
    {
      id: 6,
      title: "Color Valley",
      description: "black in color",
      price: 2500,
      img: "./images/fashion3.png",
      quantity: 2,
    },
    {
      id: 7,
      title: "Purvaja",
      description: "Best dress ever",
      price: 90500,
      img: "./images/fashion4.png",
      quantity: 2,
    },
    {
      id: 8,
      title: "Frock",
      description: "black in color",
      price: 2500,
      img: "./images/fashion1.png",
      quantity: 2,
    },
  ]; 